import Config

# Configure your database
config :velora, Velora.Repo,
  username: "postgres",
  password: "postgres",
  hostname: "localhost",
  database: "velora_dev",
  stacktrace: true,
  show_sensitive_data_on_connection_error: true,
  pool_size: 10

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we use it
# with esbuild to bundle .js and .css sources.
config :velora, VeloraWeb.Endpoint,
  # Binding to loopback ipv4 address prevents access from other machines.
  # Change to `ip: {0, 0, 0, 0}` to allow access from other machines.
  http: [ip: {127, 0, 0, 1}, port: 4000],
  url: [host: "builder.tail93695b.ts.net", scheme: "https", port: 443],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "hzLOkFX02eEpPErRfFlzxL+ppjUTCREVyTIf5euujUJ4qMSoDRVww9eJq01ZYHoT",
  watchers: [
    esbuild: {Esbuild, :install_and_run, [:default, ~w(--sourcemap=inline --watch)]},
    tailwind: {Tailwind, :install_and_run, [:default, ~w(--watch)]}
  ]

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Watch static and templates for browser reloading.
config :velora, VeloraWeb.Endpoint,
  live_reload: [
    patterns: [
      ~r"priv/static/.*(js|css|png|jpeg|jpg|gif|svg)$",
      ~r"priv/gettext/.*(po)$",
      ~r"lib/velora_web/(controllers|live|components)/.*(ex|heex)$"
    ]
  ]

# Enable dev routes for dashboard and mailbox
config :velora, dev_routes: true

# Do not include metadata nor timestamps in development logs
config :logger, :console, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

# Disable swoosh api client as it is only required for production adapters.
config :swoosh, :api_client, false

config :velora, :github_app_manifest, base_url: "https://builder.tail93695b.ts.net"

config :velora, :github_app_manifest,
  name: "Velora",
  description: "Velora GitHub App",
  public: false,
  hook_path: "/api/github/webhook",
  redirect_path: "/github/app/manifest/callback",
  setup_url: "https://builder.tail93695b.ts.net/api/github/connect/callback",
  default_events: ["push"],
  default_permissions: %{
    "contents" => "read",
    "metadata" => "read"
  }
